### ISSUE TITLE
Create docker-compose.yml example

### ISSUE THREAD

**Issue by andy5995** [andy5995/linuxdeploy-build-helper-container#14]

**Comment by andy5995** [comment]
I started on an example months ago but didn't get around yet to figuring out if it was great yet or not:

```
version: '3'

services:
  build-appimage:
    environment:
    - HOSTUID=$HOSTUID
    - HOST_SOURCE_ROOT=$HOST_SOURCE_ROOT
    container_name: linuxdeploy
    image: andy5995/linuxdeploy
    working_dir: /workspace
    command: packaging/appimage/pre-appimage.sh
    user: root
    volumes:
      - $HOST_SOURCE_ROOT:/workspace
    restart: "no"
```

I forgot why I have an '.env' file in the source root, which is used by docker-compose, and contains this line:

HOSTUID=1000
